"""add commerce payments and outbox

Revision ID: 0004_orders_payments
Revises: 0003_catalog_listings
Create Date: 2026-09-17 16:53:59.828378
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0004_orders_payments"
down_revision: str | None = "0003_catalog_listings"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_jobs",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=160), nullable=False),
        sa.Column("payload", mysql.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="pending", nullable=False),
        sa.Column("attempts", mysql.INTEGER(unsigned=True), server_default="0", nullable=False),
        sa.Column("max_attempts", mysql.INTEGER(unsigned=True), server_default="8", nullable=False),
        sa.Column("available_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("leased_until", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_jobs")),
        sa.UniqueConstraint("dedupe_key", name="uq_outbox_jobs_dedupe_key"),
    )
    op.create_index(
        "ix_outbox_jobs_status_available", "outbox_jobs", ["status", "available_at"], unique=False
    )
    op.create_table(
        "carts",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("buyer_id", mysql.BINARY(16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','converted','abandoned')", name=op.f("ck_carts_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_carts_buyer_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
    )
    op.create_index("ix_carts_buyer_status", "carts", ["buyer_id", "status"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("buyer_id", mysql.BINARY(16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="KES", nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("delivery_address_id", mysql.BINARY(16), nullable=True),
        sa.Column("reservation_expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("paid_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("version", mysql.INTEGER(unsigned=True), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'KES'", name=op.f("ck_orders_currency_kes")),
        sa.CheckConstraint(
            "status IN ('pending_payment','paid','cancelled','expired',"
            "'fulfilment','completed','refunded')",
            name=op.f("ck_orders_status_allowed"),
        ),
        sa.CheckConstraint(
            "subtotal_amount >= 0 AND total_amount >= 0", name=op.f("ck_orders_totals_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_orders_buyer_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["delivery_address_id"],
            ["addresses.id"],
            name=op.f("fk_orders_delivery_address_id_addresses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("buyer_id", "idempotency_key", name="uq_orders_buyer_idempotency"),
    )
    op.create_index("ix_orders_buyer_created", "orders", ["buyer_id", "created_at"], unique=False)
    op.create_table(
        "cart_items",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("cart_id", mysql.BINARY(16), nullable=False),
        sa.Column("listing_id", mysql.BINARY(16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_cart_items_cart_id_carts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_cart_items_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("cart_id", "listing_id", name="uq_cart_items_listing"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("order_id", mysql.BINARY(16), nullable=False),
        sa.Column("listing_id", mysql.BINARY(16), nullable=False),
        sa.Column("farmer_id", mysql.BINARY(16), nullable=False),
        sa.Column("product_name", sa.String(length=160), nullable=False),
        sa.Column("listing_title", sa.String(length=180), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("quantity_unit", sa.String(length=16), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0 AND line_total >= 0", name=op.f("ck_order_items_amounts_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["farmer_id"],
            ["users.id"],
            name=op.f("fk_order_items_farmer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_order_items_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"], unique=False)
    op.create_table(
        "order_status_history",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("order_id", mysql.BINARY(16), nullable=False),
        sa.Column("actor_user_id", mysql.BINARY(16), nullable=True),
        sa.Column("previous_status", sa.String(length=24), nullable=True),
        sa.Column("new_status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_order_status_history_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_table(
        "payments",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("order_id", mysql.BINARY(16), nullable=False),
        sa.Column("rail", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("provider_request_ref", sa.String(length=128), nullable=True),
        sa.Column("provider_transaction_ref", sa.String(length=128), nullable=True),
        sa.Column("payer_phone_e164", sa.String(length=16), nullable=True),
        sa.Column("account_reference", sa.String(length=64), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_message", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0 AND currency = 'KES'", name=op.f("ck_payments_amount_currency_valid")
        ),
        sa.CheckConstraint("rail IN ('mpesa','bank')", name=op.f("ck_payments_rail_allowed")),
        sa.CheckConstraint(
            "state IN ('created','pending_customer','processing','succeeded',"
            "'failed','cancelled','expired','reversed')",
            name=op.f("ck_payments_state_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("order_id", "idempotency_key", name="uq_payments_order_idempotency"),
        sa.UniqueConstraint(
            "provider", "provider_request_ref", name="uq_payments_provider_request"
        ),
        sa.UniqueConstraint(
            "provider", "provider_transaction_ref", name="uq_payments_provider_transaction"
        ),
    )
    op.create_index("ix_payments_order_id", "payments", ["order_id"], unique=False)
    op.create_index("ix_payments_state_updated", "payments", ["state", "updated_at"], unique=False)
    op.create_table(
        "payment_events",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("payment_id", mysql.BINARY(16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_ref", sa.String(length=160), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("payload_redacted", mysql.JSON(), nullable=False),
        sa.Column("processing_state", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_events_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
        sa.UniqueConstraint(
            "provider", "provider_event_ref", name="uq_payment_events_provider_ref"
        ),
    )
    op.create_index(
        "ix_payment_events_payment_created",
        "payment_events",
        ["payment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "payment_reconciliations",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("payment_id", mysql.BINARY(16), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("reported_amount", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider_settlement_ref", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("discrepancy_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "checked_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_reconciliations_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_reconciliations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop dependent tables in reverse creation order. MySQL may use a declared
    # composite index to support a foreign key, so dropping those indexes separately
    # before their tables raises error 1553.
    op.drop_table("payment_reconciliations")
    op.drop_table("payment_events")
    op.drop_table("payments")
    op.drop_table("order_status_history")
    op.drop_table("order_items")
    op.drop_table("cart_items")
    op.drop_table("orders")
    op.drop_table("carts")
    op.drop_table("outbox_jobs")
