"""messaging notifications and delivery

Revision ID: 0005
Revises: 0004_orders_payments
Create Date: 2026-09-17 18:25:42.032952
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0005"
down_revision: str | None = "0004_orders_payments"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_id", mysql.BINARY(16), nullable=False),
        sa.Column("buyer_id", mysql.BINARY(16), nullable=False),
        sa.Column("farmer_id", mysql.BINARY(16), nullable=False),
        sa.Column("last_message_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope_type IN ('order','listing')", name=op.f("ck_conversations_scope_type_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
            name=op.f("fk_conversations_buyer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["farmer_id"],
            ["users.id"],
            name=op.f("fk_conversations_farmer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "scope_type", "scope_id", "buyer_id", "farmer_id", name="uq_conversation_scope_members"
        ),
    )
    op.create_index(
        "ix_conversations_buyer_updated", "conversations", ["buyer_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_conversations_farmer_updated",
        "conversations",
        ["farmer_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", mysql.BINARY(16), nullable=False),
        sa.Column("messages_push", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("orders_push", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_preferences")),
    )
    op.create_table(
        "notifications",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("user_id", mysql.BINARY(16), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("data", mysql.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=160), nullable=False),
        sa.Column("read_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notifications_user_dedupe"),
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("conversation_id", mysql.BINARY(16), nullable=False),
        sa.Column("sender_id", mysql.BINARY(16), nullable=False),
        sa.Column("client_message_id", mysql.BINARY(16), nullable=False),
        sa.Column("body", mysql.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "sender_id", "client_message_id", name="uq_message_client_id"
        ),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("notification_id", mysql.BINARY(16), nullable=False),
        sa.Column("device_installation_id", mysql.BINARY(16), nullable=False),
        sa.Column("provider_message_id", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column("delivered_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','delivered','failed','skipped')",
            name=op.f("ck_notification_deliveries_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["device_installation_id"],
            ["device_installations.id"],
            name=op.f("fk_notification_deliveries_device_installation_id_device_installations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_deliveries_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "notification_id", "device_installation_id", name="uq_delivery_notification_device"
        ),
    )
    op.create_table(
        "conversation_read_states",
        sa.Column("conversation_id", mysql.BINARY(16), nullable=False),
        sa.Column("user_id", mysql.BINARY(16), nullable=False),
        sa.Column("last_read_message_id", mysql.BINARY(16), nullable=True),
        sa.Column(
            "read_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_read_states_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_read_message_id"],
            ["messages.id"],
            name=op.f("fk_conversation_read_states_last_read_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversation_read_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id", "user_id", name=op.f("pk_conversation_read_states")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_read_states")
    op.drop_table("notification_deliveries")
    op.drop_table("messages")
    op.drop_table("notifications")
    op.drop_table("notification_preferences")
    op.drop_table("conversations")
    # ### end Alembic commands ###
