"""premium subscriptions prebookings and insights

Revision ID: 0007_premium
Revises: 0006_messaging
Create Date: 2026-09-17 19:03:37.749859
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0007_premium"
down_revision: str | None = "0006_messaging"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_interval", sa.String(length=16), nullable=False),
        sa.Column("features", mysql.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "audience IN ('buyer','farmer')", name=op.f("ck_plans_audience_allowed")
        ),
        sa.CheckConstraint(
            "billing_interval IN ('month','year')", name=op.f("ck_plans_interval_allowed")
        ),
        sa.CheckConstraint("price_amount >= 0", name=op.f("ck_plans_price_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name="uq_plans_code"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("user_id", mysql.BINARY(16), nullable=False),
        sa.Column("plan_id", mysql.BINARY(16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("provider", sa.String(length=48), nullable=False),
        sa.Column("provider_subscription_ref", sa.String(length=160), nullable=True),
        sa.Column("account_reference", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("current_period_start", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("current_period_end", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("verified_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("cancelled_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','past_due','cancelled','expired')",
            name=op.f("ck_subscriptions_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_subscriptions_plan_id_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("account_reference", name="uq_subscriptions_account_reference"),
        sa.UniqueConstraint(
            "provider", "provider_subscription_ref", name="uq_subscriptions_provider_ref"
        ),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_subscriptions_user_idempotency"),
    )
    op.create_index(
        "ix_subscriptions_user_status", "subscriptions", ["user_id", "status"], unique=False
    )
    op.create_table(
        "subscription_events",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("subscription_id", mysql.BINARY(16), nullable=False),
        sa.Column("provider", sa.String(length=48), nullable=False),
        sa.Column("provider_event_ref", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("payload_redacted", mysql.JSON(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_events_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_events")),
        sa.UniqueConstraint("provider", "provider_event_ref", name="uq_subscription_events_ref"),
    )
    op.create_index(
        "ix_subscription_events_subscription_created",
        "subscription_events",
        ["subscription_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "prebookings",
        sa.Column("id", mysql.BINARY(16), nullable=False),
        sa.Column("buyer_id", mysql.BINARY(16), nullable=False),
        sa.Column("farmer_id", mysql.BINARY(16), nullable=False),
        sa.Column("product_id", mysql.BINARY(16), nullable=False),
        sa.Column("listing_id", mysql.BINARY(16), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("quantity_unit", sa.String(length=24), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("window_start", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("window_end", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('requested','accepted','rejected','cancelled','fulfilled')",
            name=op.f("ck_prebookings_status_allowed"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_prebookings_quantity_positive")),
        sa.CheckConstraint("window_end > window_start", name=op.f("ck_prebookings_window_valid")),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
            name=op.f("fk_prebookings_buyer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["farmer_id"],
            ["users.id"],
            name=op.f("fk_prebookings_farmer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_prebookings_listing_id_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_prebookings_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prebookings")),
    )
    op.create_index(
        "ix_prebookings_buyer_created", "prebookings", ["buyer_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_prebookings_farmer_status", "prebookings", ["farmer_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Let MySQL remove indexes with their tables; some indexes support foreign keys.
    op.drop_table("prebookings")
    op.drop_table("subscription_events")
    op.drop_table("subscriptions")
    op.drop_table("plans")
